--CONSULTA REALIZADA EL 22/10/2020 16:52 HS
--NO SE CONSIDERÓ LIC EN CIENCIAS DE LA EDUCACIÓN DE LA SEDE GOYA POR NO ESTAR EN EL CUADRO SOLICITADO
--SE UTILIZÓ  LA VISTA VW_LISTA_ALUMNOS_TOTAL_WEB DEL SRV114.CENTRAL_SEG, TRAE TODOS LOS ALUMNOS DE LAS COPIAS LOCALES
SELECT S.SED_DESCRIPCION, LATW.ALU_APELLIDO_AL, LATW.ALU_NOMBRE_AL,LATW.ALU_MAIL_AL, SR.SIR_DESCRIPCION,  PE.PES_DESCRIPCION
FROM SRV114.CENTRAL_SEG.DBO.VW_LISTA_ALUMNOS_TOTAL_WEB LATW --VISTA SRV114 TODOS LOS ALUMNOS DE LAS SEDES EN LA COPIA LOCAL
INNER JOIN SITUACION_REVISTA SR
ON LATW.ALU_SIR_CODIGO = SR.SIR_CODIGO
INNER JOIN SEDES S
ON LATW.SEDE = S.SED_CODIGO
INNER JOIN PLAN_ESTUDIO PE
ON LATW.ALU_PES_CAR_FAC_CODIGO = PE.PES_CAR_FAC_CODIGO  AND LATW.ALU_PES_CODIGO = PE.PES_CODIGO

--CONDICIONES
WHERE LATW.ALU_SIR_CODIGO IN(1,4,5,6,7) --ACTIVO, AQNC,REINCORPORADO PARA CURSAR, REINCOPORADO PARA RENDIR,COMPLETO CURSADO
ORDER BY LATW.SEDE, LATW.ALU_PES_CAR_FAC_CODIGO,PE.PES_DESCRIPCION, SR.SIR_CODIGO


--POSGRADO, OBTENCIÓN DE LAS ESPECIALIZACIONES

--SOLO SE CONSIDERARON LAS ESPECIALIZACIONES,SEGUN EL CUADRO ENVIADO DONDE LA COLUMNA DESCRIPCION DECÍA ESPECIALIZACIONES - POSGRADO
SELECT S.DESCRIPCION, A.APELLIDO, A.NOMBRE, A.EMAIL, SR.DESCRIPCION,  PE.DESCRIPCION  FROM POSGRADO.DBO.ALUMNOS A --646 ALUMNOS POSGRADO, 343 CON ESPECIALIZACIONES
INNER JOIN POSGRADO.DBO.SITUACION_REVISTA SR
ON A.SIT_REVISTA = SR.SIR_CODIGO 
INNER JOIN POSGRADO.DBO.SEDES S
ON A.SEDE = S.SED_CODIGO
INNER JOIN POSGRADO.DBO.PLAN_ESTUDIO PE
ON A.FACULTAD = PE.FAC_CODIGO   AND A.CARRERA = PE.CAR_CODIGO   AND A.PLAN_ESTUDIO = PE.PES_CODIGO
--CONDICIONES
WHERE A.SIT_REVISTA IN(1,5,7) --(ACTIVO, REINCORPORADO PARA CURSAR, COMPLETO CURSADO)
AND PE.DESCRIPCION LIKE '%ESPECIALIZAC%' --SOLO ESPECIALIZACIONES
ORDER BY A.SEDE, PE.FAC_CODIGO, PE.PES_CODIGO,SR.SIR_CODIGO














