

SELECT *
FROM DBO.VW_MESA_LLAMADO
WHERE MEL_FECHA = '26/02/2022'
ORDER BY MEL_HORA

SELECT *
FROM VW_MESA_LLAMADO_DOCENTES
WHERE MEL_FECHA = '21/02/2022'
AND DOC_CODIGO = 1052

-- 75194  75240 75956



SELECT *
FROM MESA_LLAMADO_WEB
WHERE MEL_MEE_CODIGO = 20885 --3012

SELECT *
FROM MESA_LLAMADO_WEB_TIPO
WHERE MESA_LLAMADO_WEB_ID = 5796 --849

SELECT *
FROM MESA_LLAMADO_WEB_ALUMNOS
WHERE MESA_LLAMADO_WEB_TIPO_ID = 4469


SELECT * FROM VW_GENERACION_ACTA_VOLANTE
WHERE MEE_CODIGO = 19856
AND MEE_ANO = 2022



declare @mesa_llamado_web_tipo_id int, @mesa int, @año int, @llamado int
--CAMBIAR LOS VALORES ANTES DE EJECUTAR
set @mesa_llamado_web_tipo_id = 4469
set @mesa = 20885
set @año = 2022
set @llamado = 2

--REGULARES
INSERT INTO [dbo].[MESA_LLAMADO_WEB_ALUMNOS]
([MESA_LLAMADO_WEB_TIPO_ID]
,[ALU_CODIGO]
,[PRESENTE]
,[FECHA_HORA_MARCACION]
,[PRESENTE_CARGA_NOTAS]
,[NOTA_ESCRITO]
,[NOTA_ORAL]
,[OBSERVACIONES_DOCENTES]
,[SALE_EN_ACTA]
,[OBSERVACIONES_NO_SALE_EN_ACTA]
,[FECHA_HORA_ULTIMA_MODIFICACION])
SELECT @mesa_llamado_web_tipo_id, ALU_CODIGO, 0, NULL, 0, NULL, NULL, NULL, CASE WHEN LEN(dbo.MESA_EXAMEN_WEB_ALUMNOS_OBSERVACION_NO_SALEN_ACTA_ESCALAR(VWGAV.SIT_ADM,VWGAV.SANCION,VWGAV.CORRELATIVA,VWGAV.VERIF_CERO,VWGAV.APROBADA,VWGAV.VERIF_EXAMENES,VWGAV.VERIF_INSCRIPCION)) = 0 THEN 1 ELSE 0 END, dbo.MESA_EXAMEN_WEB_ALUMNOS_OBSERVACION_NO_SALEN_ACTA_ESCALAR(VWGAV.SIT_ADM,VWGAV.SANCION,VWGAV.CORRELATIVA,VWGAV.VERIF_CERO,VWGAV.APROBADA,VWGAV.VERIF_EXAMENES,VWGAV.VERIF_INSCRIPCION), NULL FROM VW_GENERACION_ACTA_VOLANTE VWGAV
WHERE MEE_CODIGO = @mesa
AND MEE_ANO = @año 
AND MEL_LLAMADO = @llamado
AND IFA_LIBRE = 'N'


--EJECUTAR SOLO SI HAY LIBRES 

--LIBRES
INSERT INTO [dbo].[MESA_LLAMADO_WEB_ALUMNOS]
([MESA_LLAMADO_WEB_TIPO_ID]
,[ALU_CODIGO]
,[PRESENTE]
,[FECHA_HORA_MARCACION]
,[PRESENTE_CARGA_NOTAS]
,[NOTA_ESCRITO]
,[NOTA_ORAL]
,[OBSERVACIONES_DOCENTES]
,[SALE_EN_ACTA]
,[OBSERVACIONES_NO_SALE_EN_ACTA]
,[FECHA_HORA_ULTIMA_MODIFICACION])
SELECT @MESA_LLAMADO_WEB_TIPO, ALU_CODIGO, 0, NULL, 0, NULL, NULL, NULL, 
CASE WHEN LEN(dbo.MESA_EXAMEN_WEB_ALUMNOS_OBSERVACION_NO_SALEN_ACTA_ESCALAR(VWGAV.SIT_ADM,VWGAV.SANCION,VWGAV.CORRELATIVA,VWGAV.VERIF_CERO,VWGAV.APROBADA,VWGAV.VERIF_EXAMENES,VWGAV.VERIF_INSCRIPCION)) = 0 THEN 1 ELSE 0 END, 
dbo.MESA_EXAMEN_WEB_ALUMNOS_OBSERVACION_NO_SALEN_ACTA_ESCALAR(VWGAV.SIT_ADM,VWGAV.SANCION,VWGAV.CORRELATIVA,VWGAV.VERIF_CERO,VWGAV.APROBADA,VWGAV.VERIF_EXAMENES,VWGAV.VERIF_INSCRIPCION), NULL 
FROM VW_GENERACION_ACTA_VOLANTE VWGAV
WHERE MEE_CODIGO = @MEL_MEE_CODIGO
AND MEE_ANO = @MEL_MEE_ANO 
AND MEL_LLAMADO = @MEL_LLAMADO
AND IFA_LIBRE = 'S'

UPDATE INS_FINAL_ALUMNOS
SET IFA_SITUACION = MLLWA.OBSERVACIONES_NO_SALE_EN_ACTA
--SELECT * 
FROM MESA_LLAMADO_WEB MLLW
INNER JOIN MESA_LLAMADO_WEB_TIPO MLLWT
ON MLLW.ID = MLLWT.MESA_LLAMADO_WEB_ID
INNER JOIN MESA_LLAMADO_WEB_ALUMNOS MLLWA
ON MLLWT.ID = MLLWA.MESA_LLAMADO_WEB_TIPO_ID 
INNER JOIN INS_FINAL_ALUMNOS IFA
ON MLLW.MEL_MEE_CODIGO = IFA.IFA_MEE_CODIGO
AND MLLW.MEL_MEE_ANO = IFA.IFA_MEE_ANO
AND MLLW.MEL_LLAMADO = IFA.IFA_MEE_LLAMADO
AND MLLWA.ALU_CODIGO = IFA.IFA_ALU_CODIGO
WHERE MLLW.MEL_MEE_CODIGO = @mesa
AND MLLW.MEL_MEE_ANO = @año
AND MLLW.MEL_LLAMADO = @llamado
AND MLLWA.SALE_EN_ACTA = 0