

--alumnos del 319 que rindieron en el plan 74/17 y 450/18
--hay que cambiar el código de plan y carrera
SELECT ME.MEE_CODIGO,ME.MEE_ANO,ME.MEE_DESCRIPCION,NOF_NOTA_ORAL,ALU_APELLIDO_AL, ALU_NOMBRE_AL,
M.MAT_DESCRIPCION, PE1.PES_DESCRIPCION AS PLAN_RINDIO,
 PE2.PES_DESCRIPCION AS PLAN_ALUMNO, CONVERT(VARCHAR(10),NF.NOF_FECHA,103) FECHA_EXAMEN
 FROM MESA_EXAMEN ME
--NOTAS FINALES
INNER JOIN NOTAS_FINALES NF
ON ME.MEE_CODIGO = NF.NOF_IFA_MEE_CODIGO AND ME.MEE_ANO = NF.NOF_IFA_MEE_ANO AND NF.NOF_NOTA_ORAL > = 6
INNER JOIN ALUMNOS A
ON NF.NOF_IFA_ALU_CODIGO = A.ALU_CODIGO AND ALU_PES_CODIGO = 31 AND ALU_SIR_CODIGO IN(1,4,5,6,7)
INNER JOIN MATERIA M
ON ME.MEE_PLM_MAT_CODIGO = M.MAT_CODIGO
INNER JOIN PLAN_ESTUDIO PE1
ON ME.MEE_PLM_PES_CODIGO = PE1.PES_CODIGO
INNER JOIN PLAN_ESTUDIO PE2
ON A.ALU_PES_CODIGO = PE2.PES_CODIGO
WHERE ME.MEE_PLM_PES_CODIGO = 86 AND ME.MEE_PLM_PES_CAR_FAC_CODIGO = 5 AND ME.MEE_PLM_PES_CAR_CODIGO = 39
ORDER BY A.ALU_CODIGO
      





