
DECLARE @ALU_CODIGO INT, @CODIGO INT

DECLARE ALUMNOS_ CURSOR FOR  
select 
AP.alu_codigo

 from srv114.concentrador.[dbo].[VW_SAP] S
 INNER JOIN SRV10.POSGRADO.DBO.ALUMNOS AP
 ON S.U_SEIDORAR_IDAL = AP.ALU_CODIGO

 where
 "U_SEIDORAR_TIPOF"<>'GRADO'
 AND "U_SEIDORAR_TIPOF"<>'PRE-GRADO'
 AND "U_SEIDORAR_TIPOF"<>'POSGRADO'
 AND ("U_SEIDORAR_SITREV"=1 OR "U_SEIDORAR_SITREV"=0 )

 OPEN ALUMNOS_
  
  FETCH NEXT FROM ALUMNOS_  
   INTO @ALU_CODIGO
   
		 WHILE @@FETCH_STATUS = 0  
		 BEGIN
			SELECT @CODIGO = MAX(CODIGO) + 1  FROM SRV10.POSGRADO.DBO.HISTORICO_SITUACION_REVISTA
 
			--INSERT HISTORICO
			INSERT INTO SRV10.POSGRADO.DBO.HISTORICO_SITUACION_REVISTA
				   ([CODIGO]
				   ,[ALU_CODIGO]
				   ,[SIR_CODIGO]
				   ,[FECHA]
				   ,[FECHA_SOLICITUD]
				   ,[OBSERVACIONES]
				   ,[USUARIO])
			 VALUES
				   (@CODIGO
				   ,@ALU_CODIGO
				   ,2
				   ,'19/02/2021'
				   ,'19/02/2021'
				   ,'Baja solicitada por Mail Rene'
				   ,'ADOLFOS')
		

		--UPDATE ALUMNOS
		UPDATE SRV10.POSGRADO.DBO.ALUMNOS
			   SET
				  SIT_REVISTA = 2
				  ,FECHA_MOVIMIENTO = '19/02/2021'
				  ,OBSERVACIONES_BAJA = 'Baja solicitada por Mail Rene'    
				  ,USUARIO = 'ADOLFOS'

			 WHERE ALU_CODIGO = @ALU_CODIGO



   FETCH NEXT FROM ALUMNOS_  
   INTO @ALU_CODIGO
 END

 CLOSE ALUMNOS_  
 DEALLOCATE ALUMNOS_ 
