--OBTENGO LOS ALUMNOS QUE HICIERON CAMBIO DE PLAN 
--EN UN AÑO EN PARTICULAR

SELECT PES_DESCRIPCION AS PLAN_ORIGEN , PES_DESCRIPCION_RELAC AS PLAN_DESTINO, ALU_NRO_DOC_AL AS DNI, ALU_APELLIDO_AL + ' '+ ALU_NOMBRE_AL AS ALUMNO, 
CONVERT(VARCHAR(10),ANA_FECHA,103) AS FECHA_CAMBIO, DESCRIPCION 
FROM VW_ANTECEDENTES_ALUMNOS_COMPLETA AAC
WHERE ANA_TIA_CODIGO = 14
AND YEAR(ANA_FECHA) = 2020
AND DESCRIPCION LIKE '%PLAN%'
--ES SOLO PARA DETERMINAR SI SON DE CENTRAL O RESISTENCIA
-- SI EXISTE SON DE RESISTENCIA, SINO DE CENTRAL
AND  EXISTS (SELECT * FROM VW_ALUMNOS_EXTENSION_AULICA AEA
WHERE AEA.ALU_NRO_DOC_AL = AAC.ALU_NRO_DOC_AL AND EXT_CODIGO = 2 AND FECHA_HASTA IS NULL)
-- TERMINA CONSIDERACION CENTRAL/ RESISTENCIA
--EN LAS OTRAS SEDES QUITO DESDE EL AND EXISTS
ORDER BY PLAN_ORIGEN DESC
