--CANTIDAD DE CARRERAS DICTADAS
--SE CONSIDERA LAS CARRERAS QUE DICTARON COMISIONES EN EL 2020
--LA CONSULTA ESTÁ AL FINAL
CREATE VIEW VW_TOTALES_CARRERAS_DICTADAS_2020
AS
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDECENTRAL.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDECENTRAL.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 1 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA


UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDECENTRAL.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDECENTRAL.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 10 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA

UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDEGOYA.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDEGOYA.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 2 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA

UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDEPLIBRES.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDEPLIBRES.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 3 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA

UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDEPOSADAS.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDEPOSADAS.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 4 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA

UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDECURUZU.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDECURUZU.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 5 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA

UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDEFORMOSA.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDEFORMOSA.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 6 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA


UNION
SELECT DISTINCT  AC.SED_DESCRIPCION, C.CARRERA FROM SEDESPEÑA.DBO.VW_ALUMNOS_COMISIONES AC --SED_DESCRIPCION, FAC_CODIGO, CAR_COD
INNER JOIN SEDESPEÑA.DBO.CARRERAS C
ON AC.FAC_CODIGO = C.FAC_COD AND AC.CAR_COD = C.CAR_COD

WHERE COA_ANO = 2020 AND COM_SED_CODIGO = 11 --CAMBIAR SEDE
GROUP BY AC.SED_DESCRIPCION, C.CARRERA


--CONSULTA CON TOTALES DE CARRERAS DICTADAS POR SEDE
SELECT COUNT(*), SED_DESCRIPCION FROM VW_TOTALES_CARRERAS_DICTADAS_2020
GROUP BY SED_DESCRIPCION


