
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE Insertar_Comision
	@COM_CODIGO_ORIGEN INT,
	@SEDE_A_INSERTAR INT,
	@RETORNO INT OUTPUT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

	SET NOCOUNT ON;
	DECLARE @COM_CODIGO INT

	IF @SEDE_A_INSERTAR = 1
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDECENTRAL.DBO.COMISIONES
	      
		  
			INSERT INTO SEDECENTRAL.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END

	IF @SEDE_A_INSERTAR = 2
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDEGOYA.DBO.COMISIONES
	      
		  
			INSERT INTO SEDEGOYA.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END
	 
	 IF @SEDE_A_INSERTAR = 3
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDEPLIBRES.DBO.COMISIONES
	      
		  
			INSERT INTO SEDEPLIBRES.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END
	 
	 IF @SEDE_A_INSERTAR = 4
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDEPOSADAS.DBO.COMISIONES
	      
		  
			INSERT INTO SEDEPOSADAS.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END
	 
	 IF @SEDE_A_INSERTAR = 5
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDECURUZU.DBO.COMISIONES
	      
		  
			INSERT INTO SEDECURUZU.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END
	 
	 IF @SEDE_A_INSERTAR = 6
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDEFORMOSA.DBO.COMISIONES
	      
		  
			INSERT INTO SEDEFORMOSA.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END
	 

	IF @SEDE_A_INSERTAR = 11
	BEGIN
		     SELECT @COM_CODIGO = MAX(COM_CODIGO) + 1 FROM SEDESPEÑA.DBO.COMISIONES
	      
		  
			INSERT INTO SEDESPEÑA.dbo.COMISIONES

			SELECT @COM_CODIGO,COM_DESCRIPCION,COMISION,COM_FECHA,0,COM_TUC_CODIGO,@SEDE_A_INSERTAR,COM_TIPO_COMISION,COM_PLAN_RAIZ,COM_ACTIVA
			FROM COMISIONES WHERE COM_CODIGO = @COM_CODIGO_ORIGEN 

          SET @RETORNO = @COM_CODIGO
	END
	 
 RETURN @RETORNO

END
GO


CREATE PROCEDURE Insertar_Com_Plan
@COM_ORIGEN INT,
@COM_DESTINO INT,
@SEDE_A_INSERTAR INT
AS
BEGIN
SET NOCOUNT ON;

IF @SEDE_A_INSERTAR = 1
BEGIN
 INSERT INTO SEDECENTRAL.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END
 
IF @SEDE_A_INSERTAR = 2
BEGIN
 INSERT INTO SEDEGOYA.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END 

IF @SEDE_A_INSERTAR = 3
BEGIN
 INSERT INTO SEDEPLIBRES.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END
 
 IF @SEDE_A_INSERTAR = 4
BEGIN
 INSERT INTO SEDEPOSADAS.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 5
BEGIN
 INSERT INTO SEDECURUZU.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END


IF @SEDE_A_INSERTAR = 6
BEGIN
 INSERT INTO SEDEFORMOSA.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 11
BEGIN
 INSERT INTO SEDESPEÑA.dbo.COM_PLAN

           SELECT @COM_DESTINO, CPL_PLM_PES_CODIGO,CPL_PLM_PES_CAR_FAC_CODIGO,CPL_PLM_PES_CAR_CODIGO,CPL_PLM_MAT_CODIGO,CPL_CANTIDAD_HORAS,CPL_ORIENTACION FROM COM_PLAN
              WHERE CPL_COM_CODIGO = @COM_ORIGEN
END

END


CREATE PROCEDURE Insertar_Comisiones_Ano
@COM_ORIGEN INT,
@SEDE_A_INSERTAR INT,
@COM_DESTINO INT

AS
BEGIN

IF @SEDE_A_INSERTAR = 1
BEGIN
INSERT INTO SEDECENTRAL.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 2
BEGIN
INSERT INTO SEDEGOYA.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 3
BEGIN
INSERT INTO SEDEPLIBRES.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END


IF @SEDE_A_INSERTAR = 4
BEGIN
INSERT INTO SEDEPOSADAS.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 5
BEGIN
INSERT INTO SEDECURUZU.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 6
BEGIN
INSERT INTO SEDEFORMOSA.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END

IF @SEDE_A_INSERTAR = 11
BEGIN
INSERT INTO SEDESPEÑA.dbo.COMISIONES_ANO
			SELECT @COM_DESTINO,COA_ANO,COA_CUATRIMESTRE,COA_AUL_CODIGO,COA_CUPO,COA_CANT_INSCRIPTOS,COA_VIGENTE,COA_CANTIDAD FROM COMISIONES_ANO
			WHERE COA_COM_CODIGO = @COM_ORIGEN
END
END


CREATE PROCEDURE Insertar_Comision_Dias
@COM_ORIGEN INT,
@COM_DESTINO INT,
@SEDE_A_INSERTAR INT
as
BEGIN
    IF @SEDE_A_INSERTAR = 1
	BEGIN
	    INSERT INTO SEDECENTRAL.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END

         IF @SEDE_A_INSERTAR = 2
	BEGIN
	    INSERT INTO SEDEGOYA.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END

	   IF @SEDE_A_INSERTAR = 3
	BEGIN
	    INSERT INTO SEDEPLIBRES.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END

	   IF @SEDE_A_INSERTAR = 4
	BEGIN
	    INSERT INTO SEDEPOSADAS.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END

	   IF @SEDE_A_INSERTAR = 5
	BEGIN
	    INSERT INTO SEDECURUZU.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END

	   IF @SEDE_A_INSERTAR = 6
	BEGIN
	    INSERT INTO SEDEFORMOSA.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END

	   IF @SEDE_A_INSERTAR = 11
	BEGIN
	    INSERT INTO SEDESPEÑA.dbo.COMISION_DIAS
        SELECT @COM_DESTINO,COD_COA_ANO,COD_COA_CUATRIMESTRE,COD_DIAS,COD_HORARIO_DESDE,COD_HORARIO_HASTA FROM COMISION_DIAS
        WHERE COD_COA_COM_CODIGO = @COM_ORIGEN
	END





END


CREATE PROCEDURE Insertar_Alumno_Comision
@COM_ORIGEN INT,
@COM_DESTINO INT,
@SEDE_A_INSERTAR INT,
@ALU_CODIGO_ORIGEN INT,
@ALU_CODIGO_DESTINO INT
AS
BEGIN


IF @SEDE_A_INSERTAR = 1
BEGIN

INSERT INTO SEDECENTRAL.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 2
BEGIN

INSERT INTO SEDEGOYA.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END


IF @SEDE_A_INSERTAR = 3
BEGIN

INSERT INTO SEDEPLIBRES.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 4
BEGIN

INSERT INTO SEDEPOSADAS.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END


IF @SEDE_A_INSERTAR = 5
BEGIN

INSERT INTO SEDECURUZU.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END


IF @SEDE_A_INSERTAR = 6
BEGIN

INSERT INTO SEDEFORMOSA.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 11
BEGIN

INSERT INTO SEDESPEÑA.dbo.ALUMNO_COMISION

SELECT @COM_DESTINO,ALC_COA_ANO,ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,ALC_REGULARIZADA,ALC_APROBADA,
ALC_VENCIDA,ALC_FECHA_VIGENCIA,ALC_FECHA_INSC,ALC_LIBRE,ALC_INHABILITADO,ALC_LIBRE_PARCIAL,
ALC_PORC_INAS,ALC_OBSERV_MODIF_REG,ALC_FECHA_CREAC_REG,IAL_FECHA_MODIF_REG,ALC_USUARIO_MODIF_REG,
ALC_CONDICIONAL,ALC_MOTIVO,X,ALC_USUARIO_CREAC_REG,ALC_LIBRE_TP,ALC_ESTADO_CURSADA,
ALC_OBS, ALC_TIPO_APROB,ALC_PROVISORIA,ALC_RECUPERA
FROM ALUMNO_COMISION 

WHERE ALC_COA_COM_CODIGO = @COM_ORIGEN AND ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

END




CREATE PROCEDURE Insertar_Inasistencia_alumnos
@COM_ORIGEN INT,
@COM_DESTINO INT,
@SEDE_A_INSERTAR INT,
@ALU_CODIGO_ORIGEN INT,
@ALU_CODIGO_DESTINO INT

as
begin

IF @SEDE_A_INSERTAR = 1
BEGIN
INSERT INTO SEDECENTRAL.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 2
BEGIN
INSERT INTO SEDEGOYA.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END


IF @SEDE_A_INSERTAR = 3
BEGIN
INSERT INTO SEDEPLIBRES.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 4
BEGIN
INSERT INTO SEDEPOSADAS.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 5
BEGIN
INSERT INTO SEDECURUZU.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 6
BEGIN
INSERT INTO SEDEFORMOSA.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 11
BEGIN
INSERT INTO SEDESPEÑA.dbo.INASISTENCIA_ALUMNOS

SELECT @COM_DESTINO,IAL_ALC_COA_ANO,IAL_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,IAL_FECHA_INASISTENCIA,
IAL_CANTIDAD,IAL_TIPO,IAL_JUSTIFICA,IAL_OBSERV_MODIF_REG,IAL_FECHA_CREAC_REG,
IAL_USUARIO_CREAC_REG,IAL_FECHA_MODIF_REG,IAL_USUARIO_MODIF_REG,IAL_FALTAS,IAL_SANCION

FROM INASISTENCIA_ALUMNOS
WHERE IAL_ALC_COA_COM_CODIGO = @COM_ORIGEN AND IAL_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

end


CREATE PROCEDURE Insertar_Notas_Finales_Promocionales
@COM_ORIGEN INT,
@COM_DESTINO INT,
@SEDE_A_INSERTAR INT,
@ALU_CODIGO_ORIGEN INT,
@ALU_CODIGO_DESTINO INT

AS
BEGIN
IF @SEDE_A_INSERTAR = 1
BEGIN
INSERT INTO SEDECENTRAL.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 2
BEGIN
INSERT INTO SEDEGOYA.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 3
BEGIN
INSERT INTO SEDEPLIBRES.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 4
BEGIN
INSERT INTO SEDEPOSADAS.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 5
BEGIN
INSERT INTO SEDECURUZU.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 6
BEGIN
INSERT INTO SEDEFORMOSA.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

IF @SEDE_A_INSERTAR = 11
BEGIN
INSERT INTO SEDESPEÑA.dbo.NOTAS_FINALES_PROMOCIONALES
SELECT @COM_DESTINO, NFP_ALC_COA_ANO,NFP_ALC_COA_CUATRIMESTRE,@ALU_CODIGO_DESTINO,
NFP_NOTA_ESCRITO, NFP_NOTA_ORAL,NFP_LIBRO,NFP_FOLIO,NFP_FECHA,NFP_ORDEN 

FROM NOTAS_FINALES_PROMOCIONALES

WHERE NFP_ALC_COA_COM_CODIGO = @COM_ORIGEN AND NFP_ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN
END

END

--ver mañana si tengo que considerar el cuatrimestre de donde cursó el alumno
--MODIFICAR SP PORQUE ESTÁ MAL, PLANILLA_FORMATIVA_FECHAS trae varios registros, NO LO TUVE EN CUENTA
CREATE PROCEDURE Insertar_Fechas_Examenes
@COM_ORIGEN INT,
@COM_DESTINO INT,
@SEDE_A_INSERTAR INT

AS
BEGIN

DECLARE @COM_PLAN_RAIZ INT, @COA_ANO INT, @COA_CUATRIMESTRE INT

 SELECT @COM_PLAN_RAIZ = C.COM_PLAN_RAIZ, @COA_ANO =CA.COA_ANO, @COA_CUATRIMESTRE = COA_CUATRIMESTRE FROM COMISIONES C
 INNER JOIN COMISIONES_ANO CA
 ON C.COM_CODIGO = CA.COA_COM_CODIGO
 WHERE C.COM_CODIGO = @COM_ORIGEN

 
 IF @SEDE_A_INSERTAR = 1
 BEGIN

  INSERT INTO SEDECENTRAL.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR= @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END


 IF @SEDE_A_INSERTAR = 2
 BEGIN

  INSERT INTO SEDEGOYA.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR = @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END


  IF @SEDE_A_INSERTAR = 3
 BEGIN

  INSERT INTO SEDEPLIBRES.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR = @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END


  IF @SEDE_A_INSERTAR = 4
 BEGIN

  INSERT INTO SEDEPOSADAS.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR= @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END


  IF @SEDE_A_INSERTAR = 5
 BEGIN

  INSERT INTO SEDECURUZU.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR = @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END


 IF @SEDE_A_INSERTAR = 6
 BEGIN

  INSERT INTO SEDEFORMOSA.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR = @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END

  IF @SEDE_A_INSERTAR = 11
 BEGIN

  INSERT INTO SEDESPEÑA.dbo.FECHAS_EXAMENES
 SELECT @COM_PLAN_RAIZ,FE_MAT,@COM_DESTINO,FE_ANO,FE_CUAT,FE_PARTE,
 FE_ESPECIAL,FE_F1,FE_F2,FE_F3, FE_F4, FE_F5,FE_F6,FE_F7,FE_N_IMPRESION,
 FE_FECHA_IMP,FE_USUARIO_IMP,FE_PROCESADO FROM FECHAS_EXAMENES 
 WHERE FE_COM = @COM_ORIGEN AND FE_ANO = @COA_ANO AND FE_CARR = @COM_PLAN_RAIZ AND FE_CUAT = @COA_CUATRIMESTRE
 END


END

GO


CREATE PROCEDURE Insertar_Planilla_Formativa
@COM_ORIGEN INT,
@SEDE_A_INSERTAR INT,
@ALU_CODIGO_DESTINO INT
AS
BEGIN


DECLARE @COM_PLAN_RAIZ INT, @COA_ANO INT, @COA_CUATRIMESTRE INT, @COD_PF INT, @COD_PFF INT

 SELECT @COM_PLAN_RAIZ = C.COM_PLAN_RAIZ, @COA_ANO =CA.COA_ANO, @COA_CUATRIMESTRE = COA_CUATRIMESTRE FROM COMISIONES C
 INNER JOIN COMISIONES_ANO CA
 ON C.COM_CODIGO = CA.COA_COM_CODIGO
 WHERE C.COM_CODIGO = @COM_ORIGEN

 SELECT * FROM PLANILLA_FORMATIVA


 IF( SELECT  COUNT(*) FROM PLANILLA_FORMATIVA
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE) > 0

 BEGIN

 IF @SEDE_A_INSERTAR = 1
 BEGIN
  INSERT INTO SEDECENTRAL.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = SCOPE_IDENTITY()

 INSERT INTO SEDECENTRAL.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS int)

  INSERT SEDECENTRAL.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE

 
 END

  IF @SEDE_A_INSERTAR = 2
 BEGIN
  INSERT INTO SEDEGOYA.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = CAST(SCOPE_IDENTITY() AS int)

 INSERT INTO SEDEGOYA.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS INT)


 INSERT SEDEGOYA.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE

 
 END

 IF @SEDE_A_INSERTAR = 3
 BEGIN
  INSERT INTO SEDEPLIBRES.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = CAST(SCOPE_IDENTITY() AS int)

 INSERT INTO SEDEPLIBRES.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS INT)

  INSERT SEDEPLIBRES.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE
 
 END

 IF @SEDE_A_INSERTAR = 4
 BEGIN
  INSERT INTO SEDEPOSADAS.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = CAST(SCOPE_IDENTITY() AS INT)

 INSERT INTO SEDEPOSADAS.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS INT)

  INSERT SEDEPOSADAS.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE

 
 END


 IF @SEDE_A_INSERTAR = 5
 BEGIN
  INSERT INTO SEDECURUZU.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = CAST(SCOPE_IDENTITY() AS INT)

 INSERT INTO SEDECURUZU.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS INT)

 INSERT SEDECURUZU.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE
 
 END

 IF @SEDE_A_INSERTAR = 6
 BEGIN
  INSERT INTO SEDEFORMOSA.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = CAST(SCOPE_IDENTITY() AS INT)

 INSERT INTO SEDEFORMOSA.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS INT)

  INSERT SEDEFORMOSA.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE

 
 END

 IF @SEDE_A_INSERTAR = 11
 BEGIN
  INSERT INTO SEDESPEÑA.dbo.PLANILLA_FORMATIVA
	SELECT  PLAN_COD,@COM_ORIGEN,ANO,CUAT FROM PLANILLA_FORMATIVA
	 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT  @COD_PF = CAST(SCOPE_IDENTITY() AS INT)

 INSERT INTO SEDESPEÑA.dbo.PLANILLA_FORMATIVA_FECHA
 SELECT @COD_PF,PFF.NUMERO_E,PFF.FECHA FROM PLANILLA_FORMATIVA_FECHA PFF
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 WHERE PLAN_COD = @COM_PLAN_RAIZ AND COM_COD = @COM_ORIGEN AND ANO = @COA_ANO AND CUAT = @COA_CUATRIMESTRE

 SELECT @COD_PFF = CAST(SCOPE_IDENTITY() AS INT)

 INSERT SEDESPEÑA.dbo.PLANILLA_FORMATIVA_NOTAS
 SELECT  @COD_PFF,@ALU_CODIGO_DESTINO,PFN.NOTA FROM PLANILLA_FORMATIVA_FECHA PFF
  
 INNER JOIN PLANILLA_FORMATIVA PF
 ON PFF.COD_PF = PF.COD_PF
 INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
 ON PFF.COD_PFF = PFN.COD_PFF
 WHERE PF.PLAN_COD = @COM_PLAN_RAIZ AND PF.COM_COD = @COM_ORIGEN AND PF.ANO = @COA_ANO AND PF.CUAT = @COA_CUATRIMESTRE

 
 END

 END

END


--plan_cod, com_cod, ano, cuat
select top 0 * from PLANILLA_FORMATIVA 
select top 0 * from PLANILLA_FORMATIVA_FECHA
select top 0 * from PLANILLA_FORMATIVA_NOTAS







