
--2CONSULTAS QUE HACEN LO MISMO, LA 1ERA POR MAURO Y LA SEGUNDA POR ADOLFO
--PRIMERA echo por Mauro
--Trae los datos de los alumnos que estan cursando una materia de segundo año 2C y que estan cursando materias de 3er año 2C(Contador publico)
SELECT     COM_CODIGO, COM_DESCRIPCION, PES_CODIGO, FAC_CODIGO, CAR_CODIGO, ALU_CODIGO, MAT_CODIGO, ALC_REGULARIZADA, COM_VIGENCIA, 
                      ALC_VENCIDA, COA_ANO, COA_CUATRIMESTRE, TDC_CODIGO, TDC_DESCRIPCION, ALC_FECHA_VIGENCIA, ALC_APROBADA, ALU_APELLIDO_AL, 
                      ALU_NOMBRE_AL, ALU_NRO_DOC_AL, PES_DESCRIPCION, DOM_TELEFONO, CAR_DESCRIPCION, FAC_DESCRIPCION, MAT_DESCRIPCION, 
                      ALC_FECHA_INSC, PLM_PENALIZACION, ALC_LIBRE, APELLIDO, PLM_OPTATIVA, ALC_INHABILITADO, CUATRIMESTRE_CURSADA, ALU_SIR_CODIGO, 
                      COM_TIPO_COMISION, PLM_TIPO, PLM_REM_CODIGO_REGIMEN, REM_DESCRIPCION, HORARIO, COM_SED_CODIGO, SED_DESCRIPCION, FOOTER,
                       ALC_CONDICIONAL, ALC_MOTIVO, PLM_ANUAL, ALC_LIBRE_PARCIAL, ALC_LIBRE_TP, ESTADO_CURSADA, ALC_ESTADO_CURSADA, 
                      ALC_FECHA_CREAC_REG, ALC_USUARIO_CREAC_REG, ALU_FECHA_INGRESO_AL, ALC_TIPO_APROB, ALC_PORC_INAS, PLM_TIPOCURSO, 
                      ALC_PROVISORIA, CONDICIONAL, COM_ACTIVA, COM_PLAN_RAIZ, AÑO_REAL, CUAT_REAL, REG_REAL, REGIMEN_REAL, PLM_ANO, 
                      PLM_CUATRIMESTRE, MAT_ANALOGA, COMISION, PES_CODIGO AS Expr1
FROM         VW_ALUMNOS_COMISIONES vac
WHERE     PES_CODIGO IN (1, 13, 35, 42) AND AÑO_REAL= 3 AND (COA_ANO = 2013) AND (COA_CUATRIMESTRE = '2')
AND EXISTS(SELECT     COM_CODIGO, COM_DESCRIPCION, PES_CODIGO, FAC_CODIGO, CAR_CODIGO, ALU_CODIGO, MAT_CODIGO, ALC_REGULARIZADA, COM_VIGENCIA, 
                      ALC_VENCIDA, COA_ANO, COA_CUATRIMESTRE, TDC_CODIGO, TDC_DESCRIPCION, ALC_FECHA_VIGENCIA, ALC_APROBADA, ALU_APELLIDO_AL, 
                      ALU_NOMBRE_AL, ALU_NRO_DOC_AL, PES_DESCRIPCION, DOM_TELEFONO, CAR_DESCRIPCION, FAC_DESCRIPCION, MAT_DESCRIPCION, 
                      ALC_FECHA_INSC, PLM_PENALIZACION, ALC_LIBRE, APELLIDO, PLM_OPTATIVA, ALC_INHABILITADO, CUATRIMESTRE_CURSADA, ALU_SIR_CODIGO, 
                      COM_TIPO_COMISION, PLM_TIPO, PLM_REM_CODIGO_REGIMEN, REM_DESCRIPCION, HORARIO, COM_SED_CODIGO, SED_DESCRIPCION, FOOTER,
                       ALC_CONDICIONAL, ALC_MOTIVO, PLM_ANUAL, ALC_LIBRE_PARCIAL, ALC_LIBRE_TP, ESTADO_CURSADA, ALC_ESTADO_CURSADA, 
                      ALC_FECHA_CREAC_REG, ALC_USUARIO_CREAC_REG, ALU_FECHA_INGRESO_AL, ALC_TIPO_APROB, ALC_PORC_INAS, PLM_TIPOCURSO, 
                      ALC_PROVISORIA, CONDICIONAL, COM_ACTIVA, COM_PLAN_RAIZ, AÑO_REAL, CUAT_REAL, REG_REAL, REGIMEN_REAL, PLM_ANO, 
                      PLM_CUATRIMESTRE, MAT_ANALOGA, COMISION, PES_CODIGO AS Expr1
FROM         VW_ALUMNOS_COMISIONES
WHERE   VW_ALUMNOS_COMISIONES.ALU_CODIGO = vac.ALU_CODIGO AND   (PES_CODIGO IN (1, 13, 35, 42)) AND (MAT_CODIGO = 7) AND (COA_ANO = 2013) AND (COA_CUATRIMESTRE = '2') AND COM_VIGENCIA = 1)
ORDER BY ALU_CODIGO ASC




--SEGUNDA echo por Adolfo
--Trae los datos de los alumnos que estan cursando una materia de segundo año 2C y que estan cursando materias de 3er año 2C(Contador publico)

SELECT    ac1.ALU_CODIGO, ac1.ALU_APELLIDO_AL, ac1.ALU_NOMBRE_AL, ac1.CUAT_REAL,ac1.AÑO_REAL,
                      ac1.MAT_DESCRIPCION,ac2.CUAT_REAL ,ac2.AÑO_REAL,ac2.MAT_DESCRIPCION, ac1.CUATRIMESTRE_CURSADA    
FROM         VW_ALUMNOS_COMISIONES ac1
INNER JOIN VW_ALUMNOS_COMISIONES ac2
ON ac1.ALU_CODIGO = ac2.ALU_CODIGO 
WHERE     (ac1.FAC_CODIGO = 1) AND (ac1.COA_ANO = 2013) AND (ac1.COA_CUATRIMESTRE = '2') AND (ac1.PES_CODIGO = 42) AND (ac1.CAR_CODIGO = 12) AND (ac1.AÑO_REAL = 2) 
                      AND (ac1.CUAT_REAL = 2) AND (ac1.COM_VIGENCIA = '1') AND (ac1.MAT_CODIGO = 7) AND (ac2.FAC_CODIGO = 1) AND (ac2.COA_ANO = 2013) AND (ac2.COA_CUATRIMESTRE = '2') AND (ac2.PES_CODIGO = 42) AND (ac2.CAR_CODIGO = 12) AND (ac2.AÑO_REAL = 3) 
                      AND (ac2.CUAT_REAL = 2)
 ORDER BY ac1.ALU_CODIGO asc
 





--LISTADO DE ALUMNOS QUE CURSAN DERECHO DE EMPRESAS EN CRISIS Y OTRAS MATERIAS DE 3ERO Y CUARTO

SELECT      
                      ac.ALU_APELLIDO_AL, ac.ALU_NOMBRE_AL, ac.ALU_NRO_DOC_AL, 
                       ac.COMISION,  ac.PES_DESCRIPCION, ac.MAT_DESCRIPCION, 
                      AC1.MAT_DESCRIPCION AS Materias_3er_4to, ac.COA_ANO, ac.COA_CUATRIMESTRE, ac.ALU_CODIGO
FROM         dbo.VW_ALUMNOS_COMISIONES AS ac INNER JOIN
                      dbo.VW_ALUMNOS_COMISIONES AS AC1 ON ac.ALU_CODIGO = AC1.ALU_CODIGO
WHERE     (ac.FAC_CODIGO = 1) AND (ac.PES_CODIGO = 42) AND (ac.MAT_CODIGO = 512) AND (ac.COM_VIGENCIA = '1')  AND 
                      (ac.COA_ANO = 2013) AND (ac.COA_CUATRIMESTRE = '2') AND (AC1.FAC_CODIGO = 1) AND (AC1.PES_CODIGO = 42) AND (AC1.COM_VIGENCIA = '1') 
                      AND (AC1.COA_ANO = 2013) AND (AC1.COA_CUATRIMESTRE = '2') AND (AC1.AÑO_REAL IN (3, 4)) AND (ac1.MAT_CODIGO <> 512)
ORDER BY ac.ALU_CODIGO