--ALUMNOS CON ANTECEDENTE 8 POR TRANSICION MULTIPLE EN POSADAS





--VERIFICAR SI TRAE LOS DATOS CORRECTOS
--NO OLVIDAR DEL AÑO 2019

--SELECT DISTINCT AAC.ALU_APELLIDO_AL, AAC.ALU_NOMBRE_AL, AAC.PES_DESCRIPCION, AAC.PES_DESCRIPCION_RELAC, AAC.MAT_DESCRIPCION,
--AAC.MAT_DESCRIPCION_RELAC, YEAR(AAC.FECHA_INICIO) as AÑO
--FROM VW_ANTECEDENTES_ALUMNOS_COMPLETA AAC
--INNER JOIN VW_TRANSICION_MULTIPLE_ABOGACIA_319 TMA
--ON AAC.Plan_Est = TMA.RVN_PLM_PES_CODIGO_V AND AAC.Facultad = TMA.RVN_PLM_PES_CAR_FAC_CODIGO_V AND AAC.Carrera = TMA.RVN_PLM_PES_CAR_CODIGO_V AND AAC.Materia = TMA.RVN_PLM_MAT_CODIGO_V
--WHERE AAC.Ana_Tia_Codigo = 8
--AND AAC.Plan_Est = 31
--AND YEAR(Fecha_Inicio) = 2020 --SOLO 2020
--GROUP BY AAC.ALU_APELLIDO_AL, AAC.ALU_NOMBRE_AL, AAC.PES_DESCRIPCION, AAC.PES_DESCRIPCION_RELAC, AAC.MAT_DESCRIPCION, AAC.MAT_DESCRIPCION_RELAC, AAC.Ana_Fecha, AAC.Materia, YEAR(AAC.FECHA_INICIO)  
----HAVING COUNT(AAC.Materia) >1

--ORDER BY ALU_APELLIDO_AL, ALU_NOMBRE_AL,MAT_DESCRIPCION


SELECT AAC.ALU_APELLIDO_AL, AAC.ALU_NOMBRE_AL, PRVN.PES_DESC_VIEJO, PRVN.PES_DESC_NUEVO,PRVN.MAT_DESC_VIEJO,  PRVN.MAT_DESC_NUEVO, year(aac.Fecha_Inicio) AS AÑO
FROM VW_TRANSICION_MULTIPLE_ABOGACIA_319 AS RVN
INNER JOIN VW_PLAN_RELACION_VIEJO_NUEVO AS PRVN
ON RVN.RVN_PLM_PES_CODIGO_V = PRVN.RVN_PLM_PES_CODIGO_V 
	AND RVN.RVN_PLM_PES_CAR_CODIGO_V = PRVN.RVN_PLM_PES_CAR_CODIGO_V
	AND RVN.RVN_PLM_PES_CAR_FAC_CODIGO_V = PRVN.RVN_PLM_PES_CAR_FAC_CODIGO_V
	AND RVN.RVN_PLM_MAT_CODIGO_V = PRVN.RVN_PLM_MAT_CODIGO_V
	AND RVN.RVN_PLM_PES_CODIGO_N = PRVN.RVN_PLM_PES_CODIGO_N

INNER JOIN VW_ANTECEDENTES_ALUMNOS_COMPLETA AAC
ON AAC.Plan_Est = RVN.RVN_PLM_PES_CODIGO_V AND AAC.Facultad = RVN.RVN_PLM_PES_CAR_FAC_CODIGO_V AND AAC.Carrera = RVN.RVN_PLM_PES_CAR_CODIGO_V 
AND AAC.Materia = RVN.RVN_PLM_MAT_CODIGO_V AND AAC.Materia_Relac = PRVN.RVN_PLM_MAT_CODIGO_N AND AAC.Facultad_Relac = PRVN.RVN_PLM_PES_CAR_FAC_CODIGO_V
AND AAC.Carrera_Relac = PRVN.RVN_PLM_PES_CAR_CODIGO_N AND AAC.Plan_Est_Relac = PRVN.RVN_PLM_PES_CODIGO_N
WHERE AAC.Ana_Tia_Codigo = 8
AND AAC.Plan_Est = 31
AND YEAR(AAC.Fecha_Inicio) = 2020
ORDER BY ALU_APELLIDO_AL, ALU_NOMBRE_AL,MAT_DESCRIPCION



