DECLARE @ASIGNACIONES TABLE(
DOC_CODIGO INT,
SEDE INT,
APELLIDO VARCHAR(200),
NOMBRE VARCHAR (200),
MAIL VARCHAR(200),
SEDE_VINCULO INT,
DNI INT,
TEL_FIJO VARCHAR(30),
TEL_MOVIL VARCHAR(30),
DIRECCION VARCHAR(200),
LOCALIDAD VARCHAR (200),
PROVINCIA VARCHAR(200))

DECLARE @TITULOS_POSGRADO TABLE
(LEG_CODIGO INT,
SED_CODIGO INT,
TIPO_TITULO_DESCRIPCION VARCHAR(100),
TITULO VARCHAR(200),
ESTADO VARCHAR(200))



INSERT INTO @ASIGNACIONES 
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION FROM dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDEGOYA.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDEGOYA.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDEPLIBRES.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDEPLIBRES.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDEPOSADAS.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDEPOSADAS.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDECURUZU.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDECURUZU.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDEFORMOSA.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDEFORMOSA.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDEMERCEDES.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDEMERCEDES.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV

UNION
SELECT L.LEG_CODIGO, L.SEDE, L.APELLIDO, L.NOMBRE, (ISNULL(L.MAIL,'-') + ' - ' + ISNULL(L.MAIL_2,'-')) AS MAIL, AD.SED_CODIGO, L.NUMERO_DOC, L.TEL_PART,L.TEL_MOVIL, L.DIRECCION_RES, loc.LOCAL_DESCRIP, pro.PROV_DESCRIPCION  FROM SEDEAVELLANEDA.dbo.ASIGNACIONES_DOCENTES AD
INNER JOIN SEDEAVELLANEDA.dbo.LEGAJOS L
ON AD.DOC_CODIGO = L.LEG_CODIGO
AND AD.SEDE = L.SEDE
INNER JOIN dbo.LOCALIDAD loc
on loc.COD_LOCALIDAD = L.LOCALIDAD_RES
INNER JOIN dbo.PROVINCIA pro
on pro.PROV_CODIGO = loc.COD_PROV


INSERT INTO @TITULOS_POSGRADO
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION 
FROM dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDEGOYA.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDEPLIBRES.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDEPOSADAS.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDECURUZU.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDEFORMOSA.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDEMERCEDES.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)
UNION
SELECT LEG_CODIGO, SED_CODIGO, TIPO_TITULO_DESCRIPCION, TITULO, ESTADO_DESCRIPCION FROM SEDEAVELLANEDA.dbo.VW_ESTUDIOS_PERSONAL
WHERE TIPO_TITULO IN (6) AND ESTADO IN (4,5,6)

SELECT DISTINCT ASIG.DNI, ASIG.APELLIDO, ASIG.NOMBRE, ASIG.TEL_FIJO, ASIG.TEL_MOVIL,  ASIG.MAIL, TP.TIPO_TITULO_DESCRIPCION, TP.TITULO, TP.ESTADO, ASIG.DIRECCION, ASIG.LOCALIDAD, ASIG.PROVINCIA FROM @ASIGNACIONES ASIG
INNER JOIN @TITULOS_POSGRADO TP
ON
ASIG.DOC_CODIGO = TP.LEG_CODIGO
AND
ASIG.SEDE = TP.SED_CODIGO
INNER JOIN SEDES S
ON ASIG.SEDE_VINCULO = S.SED_CODIGO
ORDER BY  ASIG.APELLIDO ASC, ASIG.NOMBRE ASC




