WITH FALTAS_(FAC, CARR, AUS1, TARD1, OM1, AUS2, TARD2, OM2, AUS3, TARD3, OM3, AUS4, TARD4, OM4,
AUS5, TARD5, OM5, AUS6, TARD6, OM6, AUS7, TARD7, OM7) AS
(SELECT FACULTAD, CARRERA, AUSENTE AS AUSENTE1, TARDANZAS AS TARDANZAS1, OMISIONES AS OMISIONES1,
NULL AS AUSENTE2,NULL AS TARDANZAS2, NULL AS OMISIONES2,
NULL AS AUSENTE3,NULL AS TARDANZAS3, NULL AS OMISIONES3,
NULL AS AUSENTE4,NULL AS TARDANZAS4, NULL AS OMISIONES4,
NULL AS AUSENTE5,NULL AS TARDANZAS5, NULL AS OMISIONES5,
NULL AS AUSENTE6,NULL AS TARDANZAS6, NULL AS OMISIONES6,
NULL AS AUSENTE7,NULL AS TARDANZAS7, NULL AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Central'
UNION
SELECT FACULTAD, CARRERA, NULL AS AUSENTE1, NULL AS TARDANZAS1, NULL AS OMISIONES1, 
AUSENTE AS AUSENTE2, TARDANZAS AS TARDANZAS2, OMISIONES AS OMISIONES2,
NULL AS AUSENTE3,NULL AS TARDANZAS3, NULL AS OMISIONES3,
NULL AS AUSENTE4,NULL AS TARDANZAS4, NULL AS OMISIONES4,
NULL AS AUSENTE5,NULL AS TARDANZAS5, NULL AS OMISIONES5,
NULL AS AUSENTE6,NULL AS TARDANZAS6, NULL AS OMISIONES6,
NULL AS AUSENTE7,NULL AS TARDANZAS7, NULL AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Regional Formosa'
UNION
SELECT FACULTAD, CARRERA, NULL AS AUSENTE1, NULL AS TARDANZAS1, NULL AS OMISIONES1, 
NULL AS AUSENTE2, NULL AS TARDANZAS2, NULL AS OMISIONES2,
AUSENTE AS AUSENTE3, TARDANZAS AS TARDANZAS3, OMISIONES AS OMISIONES3,
NULL AS AUSENTE4,NULL AS TARDANZAS4, NULL AS OMISIONES4,
NULL AS AUSENTE5,NULL AS TARDANZAS5, NULL AS OMISIONES5,
NULL AS AUSENTE6,NULL AS TARDANZAS6, NULL AS OMISIONES6,
NULL AS AUSENTE7,NULL AS TARDANZAS7, NULL AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Regional Posadas'
UNION
SELECT FACULTAD, CARRERA, NULL AS AUSENTE1, NULL AS TARDANZAS1, NULL AS OMISIONES1, 
NULL AS AUSENTE2, NULL AS TARDANZAS2, NULL AS OMISIONES2,
NULL AS AUSENTE3, NULL AS TARDANZAS3, NULL AS OMISIONES3,
AUSENTE AS AUSENTE4, TARDANZAS AS TARDANZAS4, OMISIONES AS OMISIONES4,
NULL AS AUSENTE5,NULL AS TARDANZAS5, NULL AS OMISIONES5,
NULL AS AUSENTE6,NULL AS TARDANZAS6, NULL AS OMISIONES6,
NULL AS AUSENTE7,NULL AS TARDANZAS7, NULL AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Regional Goya'
UNION
SELECT FACULTAD, CARRERA, NULL AS AUSENTE1, NULL AS TARDANZAS1, NULL AS OMISIONES1, 
NULL AS AUSENTE2, NULL AS TARDANZAS2, NULL AS OMISIONES2,
NULL AS AUSENTE3, NULL AS TARDANZAS3, NULL AS OMISIONES3,
NULL AS AUSENTE4, NULL AS TARDANZAS4, NULL AS OMISIONES4,
AUSENTE AS AUSENTE5, TARDANZAS AS TARDANZAS5, OMISIONES AS OMISIONES5,
NULL AS AUSENTE6,NULL AS TARDANZAS6, NULL AS OMISIONES6,
NULL AS AUSENTE7,NULL AS TARDANZAS7, NULL AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Regional Curuzú Cuatiá'
UNION
SELECT FACULTAD, CARRERA, NULL AS AUSENTE1, NULL AS TARDANZAS1, NULL AS OMISIONES1, 
NULL AS AUSENTE2, NULL AS TARDANZAS2, NULL AS OMISIONES2,
NULL AS AUSENTE3, NULL AS TARDANZAS3, NULL AS OMISIONES3,
NULL AS AUSENTE4, NULL AS TARDANZAS4, NULL AS OMISIONES4,
NULL AS AUSENTE5, NULL AS TARDANZAS5, NULL AS OMISIONES5,
AUSENTE AS AUSENTE6, TARDANZAS AS TARDANZAS6, OMISIONES AS OMISIONES6,
NULL AS AUSENTE7,NULL AS TARDANZAS7, NULL AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Regional Paso de los Libres'
UNION
SELECT FACULTAD, CARRERA, NULL AS AUSENTE1, NULL AS TARDANZAS1, NULL AS OMISIONES1, 
NULL AS AUSENTE2, NULL AS TARDANZAS2, NULL AS OMISIONES2,
NULL AS AUSENTE3, NULL AS TARDANZAS3, NULL AS OMISIONES3,
NULL AS AUSENTE4, NULL AS TARDANZAS4, NULL AS OMISIONES4,
NULL AS AUSENTE5, NULL AS TARDANZAS5, NULL AS OMISIONES5,
NULL AS AUSENTE6, NULL AS TARDANZAS6, NULL AS OMISIONES6,
AUSENTE AS AUSENTE7, TARDANZAS AS TARDANZAS7, OMISIONES AS OMISIONES7 
FROM dbo.ESTADISTICAS_DOCENTES_CARRERA (2016,1,'07/03/2016','30/04/2016')
WHERE SEDE = 'Regional Resistencia')
SELECT FAC, CARR, SUM(AUS1) AS AUS1, SUM(TARD1) AS TARD1, SUM(OM1) AS OM1, 
SUM(AUS2) AS AUS2, SUM(TARD2) AS TARD2, SUM(OM2) AS OM2,
SUM(AUS3) AS AUS3, SUM(TARD3) AS TARD3, SUM(OM3) AS OM3,
SUM(AUS4) AS AUS4, SUM(TARD4) AS TARD4, SUM(OM4) AS OM4,
SUM(AUS5) AS AUS5, SUM(TARD5) AS TARD5, SUM(OM5) AS OM5,
SUM(AUS6) AS AUS6, SUM(TARD6) AS TARD6, SUM(OM6) AS OM6,
SUM(AUS7) AS AUS7, SUM(TARD7) AS TARD7, SUM(OM7) AS OM7
FROM FALTAS_
GROUP BY FAC, CARR