

-- 3- Archivo Definitivo

USE EXPEDIENTESUCP

SELECT * FROM VISTA_EXPEDIENTES

SELECT * FROM ESTADO

SP_HELPTEXT VISTA_EXPEDIENTES


CREATE VIEW dbo.Vista_Expedientes_Adolfo  
AS  
SELECT     TOP (100) PERCENT dbo.MESA_ENTRADA.ID, dbo.MESA_ENTRADA.ANO, dbo.SEDES.SED_DESCRIPCION, dbo.MESA_ENTRADA.SED_CODIGO,   
                      dbo.MESA_ENTRADA.ESTADO, dbo.MESA_ENTRADA.FECHA_CREACION_REG, dbo.MESA_ENTRADA.FECHA_HORA_INICIAL,   
                      dbo.MESA_ENTRADA.COD_OBJ, dbo.MESA_ENTRADA.FAC_CODIGO, dbo.MESA_ENTRADA.NRO_EXPTE, dbo.OBJETOS.Detalle_Obj,   
                      dbo.MESA_ENTRADA.TIPO_INICIADOR, dbo.MESA_ENTRADA.FECHA_TENTATIVA, dbo.MESA_ENTRADA.COD_INICIADOR, e.est_desc, RTRIM(L.APELLIDO + ', ' + L.NOMBRE)  AS DOCENTE, 
					  A.INICIADOR AS ALUMNO, PA.PERSONAL_ADMIN
FROM         dbo.MESA_ENTRADA INNER JOIN  
                      dbo.SEDES ON dbo.MESA_ENTRADA.SED_CODIGO = dbo.SEDES.SED_CODIGO INNER JOIN  
                      dbo.OBJETOS ON dbo.MESA_ENTRADA.COD_OBJ = dbo.OBJETOS.Cod_Obj  
					  inner join estado e
					  on mesa_entrada.estado = e.est_id
					 
					  --DOCENTES, TIPO_INICIADOR = 1
					  LEFT JOIN SRV10.SEDECENTRAL.DBO.LEGAJOS L 
					  ON L.LEG_CODIGO = MESA_ENTRADA.COD_INICIADOR AND MESA_ENTRADA.TIPO_INICIADOR = 1 AND MESA_ENTRADA.SED_CODIGO = L.SEDE 

					  --ALUMNOS
					  LEFT JOIN VW_ALUMNOS_SEDES A
					  ON A.ALU_CODIGO = MESA_ENTRADA.COD_INICIADOR AND MESA_ENTRADA.TIPO_INICIADOR = 2 AND MESA_ENTRADA.SED_CODIGO = A.ALU_SED_CODIGO

					  --PERSONAL_ADMINISTRATIVO
					  LEFT JOIN VW_PERSONAL_ADMIN PA
					  ON MESA_ENTRADA.COD_INICIADOR = PA.ID AND MESA_ENTRADA.TIPO_INICIADOR = 3


					  WHERE MESA_ENTRADA.ESTADO IN (1,2)
					 
					 CREATE VIEW VW_PERSONAL_ADMIN
					 AS
					 SELECT A.ID, RTRIM(PA.NOMBRE)+ ', '+RTRIM( PA.APELLIDO) AS PERSONAL_ADMIN FROM PERSONAL_ADMIN PA
					 INNER JOIN ASIGNACION A
					 ON PA.COD_PERSONAL = A.COD_PERSONAL
			
					 --8932
					 select top 1 * from personal_admin --cod_personal, apellido,nombre
					select top 1 * from asignacion  --cod_personal, id

					
				

