
--GRADUADOS EN PANDEMIA
--SE CONSIDERÓ A LOS QUE SE GRADUARON DESDE LA FECHA DE INICIO DEL CUATRIMESTRE 2020 1ER CUATRIMESTRE HASTA LA FECHA ACTUAL
SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDEGOYA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDEGOYA.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDEPLIBRES.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDEPLIBRES.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDEPOSADAS.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDEPOSADAS.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDECURUZU.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDECURUZU.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDEFORMOSA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDEFORMOSA.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDESPEÑA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDESPEÑA.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION

UNION 

SELECT EXT_DESCRIPCION, COUNT(*) AS GRADUADOS from SEDEAVELLANEDA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL
WHERE ALU_SIR_CODIGO = 8
and year(ALU_FECHA_BAJA_AL) = 2020
AND ALU_FECHA_BAJA_AL >=(SELECT FECHA_INICIO FROM SEDEAVELLANEDA.DBO.ANIO_CUATRIMESTRE WHERE ANO = 2020 AND CUATRIMESTRE = 1) 
GROUP BY EXT_DESCRIPCION





--Corrientes			130
--Curuzu Cuatia			27
--Formosa				98
--Goya					71
--Paso de los Libres	15
--Posadas				125
--Resistencia			50
--Sáenz Peña			14


