
DECLARE @FECHA_INICIO VARCHAR(12)
DECLARE @FECHA_CARGO_LEGAJO VARCHAR(12)

DECLARE @ANO INT, @CUATRIMESTRE INT
SET @ANO = 2021
SET @CUATRIMESTRE = 1

SELECT @FECHA_INICIO = FECHA_INICIO FROM ANIO_CUATRIMESTRE WHERE ANO = @ANO AND CUATRIMESTRE = @CUATRIMESTRE

SELECT @FECHA_CARGO_LEGAJO = '30/03/'+ CONVERT(VARCHAR(4), YEAR(@FECHA_INICIO)) 

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  and EXT_CODIGO = 1
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  --order by AEAT.CARRERA
  
  UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDEGOYA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDEGOYA.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDEGOYA.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDEGOYA.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  --and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  

    UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDEPLIBRES.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDEPLIBRES.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDEPLIBRES.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDEPLIBRES.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  --and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  

    UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDEPOSADAS.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDEPOSADAS.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDEPOSADAS.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDEPOSADAS.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  --and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  
    UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDECURUZU.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDECURUZU.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDECURUZU.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDECURUZU.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  --and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  

    UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDEFORMOSA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDEFORMOSA.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDEFORMOSA.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDEFORMOSA.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  --and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  
    UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDECENTRAL.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDECENTRAL.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDECENTRAL.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDECENTRAL.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  
    UNION

  
  SELECT  COUNT(*) ,AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  FROM  SEDESPEÑA.DBO.VW_ALUMNOS_EXTENSION_AULICA_TOTAL AEAT
  INNER JOIN SEDESPEÑA.DBO.ALUMNOS A
  ON AEAT.ALU_CODIGO = A.ALU_CODIGO

  WHERE SEDESPEÑA.dbo.F_CAMBIOS_PLAN_MAL( A.ALU_PES_CAR_FAC_CODIGO, AEAT.CAR_COD, A.ALU_PES_CODIGO, A.ALU_CODIGO_ANT, A.ALU_SED_CODIGO) = 1
  AND SEDESPEÑA.dbo.Fecha_ingreso_Real(A.ALU_CODIGO) = @FECHA_INICIO
  AND A.ALU_FECHA_DIA_AL <= @FECHA_CARGO_LEGAJO
  --and EXT_CODIGO = 2
  and A.ALU_SIR_CODIGO <> 12
  group by AEAT.CARRERA, YEAR(a.ALU_FECHA_INGRESO_AL), AEAT.EXT_DESCRIPCION  
  
  ORDER BY AEAT.EXT_DESCRIPCION, AEAT.CARRERA