
--PARAMETROS
--DECLARE @ALU_CODIGO_ORIGEN INT
--,@ALU_CODIGO_DESTINO INT
--,@SEDE_A_INSERTAR INT
--,@COM_CODIGO_ORIGEN INT
--,@COM_CODIGO_DESTINO INT --EL CÒDIGO DE COMISIÒN A INSERTAR
--,@COA_ANO_ORIGEN INT
--,@COA_CUATRIMESTRE_ORIGEN INT
--,@PES_CODIGO_ORIGEN INT

--SET @ALU_CODIGO_ORIGEN = 6373
--SET @COM_CODIGO_ORIGEN = 1940
--SET @COA_ANO_ORIGEN = 2010
--SET @COA_CUATRIMESTRE_ORIGEN = 1
--SET @ALU_CODIGO_DESTINO = 878
--SET @SEDE_A_INSERTAR = 11


CREATE PROCEDURE Insertar_Planilla_Formativa
@ALU_CODIGO_ORIGEN INT,
@ALU_CODIGO_DESTINO INT,
@SEDE_A_INSERTAR INT,
@COM_CODIGO_ORIGEN INT,
@COM_CODIGO_DESTINO INT,
@COA_ANO_ORIGEN INT,
@COA_CUATRIMESTRE_ORIGEN INT,
@PES_CODIGO_ORIGEN INT

AS 
BEGIN TRY
BEGIN TRAN


DECLARE @PLAN_ORIGEN INT




select @PLAN_ORIGEN = C.COM_PLAN_RAIZ from ALUMNO_COMISION AC
INNER JOIN COMISIONES C
ON AC.ALC_COA_COM_CODIGO = C.COM_CODIGO
WHERE AC.ALC_ALU_CODIGO = @ALU_CODIGO_ORIGEN AND AC.ALC_COA_COM_CODIGO = @COM_CODIGO_ORIGEN AND AC.ALC_COA_ANO = @COA_ANO_ORIGEN AND AC.ALC_COA_CUATRIMESTRE = @COA_CUATRIMESTRE_ORIGEN

 

--DETERMINAMOS QUE EXISTE ICES CARGADOS PARA EL ALUMNO EN UNA COMISION,AÑO,CUATRIMESTRE
IF EXISTS(SELECT PF.COM_COD,PF.ANO, PF.CUAT,PF.PLAN_COD FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN)
BEGIN

DECLARE @COD_PF INT, @NUMERO_E INT, @FECHA DATETIME, @COD_PFF INT, @COD_ALUMNO INT, @NOTA INT




IF @SEDE_A_INSERTAR = 1

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDECENTRAL.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDECENTRAL.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDECENTRAL.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END




IF @SEDE_A_INSERTAR = 2

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDEGOYA.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDEGOYA.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDEGOYA.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END




IF @SEDE_A_INSERTAR = 3

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDEPLIBRES.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDEPLIBRES.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDEPLIBRES.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END



IF @SEDE_A_INSERTAR = 4

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDEPOSADAS.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDEPOSADAS.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDEPOSADAS.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END



IF @SEDE_A_INSERTAR = 5

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDECURUZU.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDECURUZU.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDECURUZU.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END


IF @SEDE_A_INSERTAR = 6

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDEFORMOSA.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDEFORMOSA.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDEFORMOSA.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END



IF @SEDE_A_INSERTAR = 11

BEGIN

--INSERTO EN PLANILLA_FORMATIVA 
INSERT SEDESPEÑA.dbo.PLANILLA_FORMATIVA

SELECT  PF.PLAN_COD, @COM_CODIGO_DESTINO, PF.ANO, PF.CUAT  FROM PLANILLA_FORMATIVA PF
INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
ON PF.COD_PF = PFF.COD_PF
INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
ON PFF.COD_PFF = PFN.COD_PFF
WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
--OBTENGO EL ÚTLIMO COD_PF INSERTADO EN DESTINO
SELECT @COD_PF = CAST(SCOPE_IDENTITY() AS int)

    --CURSOR CON LOS DATOS DE ORIGEN A INSERTAR EN DESTINO (PLANILLA_FORMATIVA_FECHAS y PLANILLA_FORMATIVA_NOTAS) 
     --RECORRO CURSOR E INSERTO EN PLANILLA_FORMATIVA_FECHAS
 DECLARE CPLANILLA_FORMATIVA CURSOR
 FOR 
    SELECT  PFF.NUMERO_E,PFF.FECHA,PFN.COD_ALUMNO,PFN.NOTA FROM PLANILLA_FORMATIVA PF
	INNER JOIN PLANILLA_FORMATIVA_FECHA PFF
	ON PF.COD_PF = PFF.COD_PF
	INNER JOIN PLANILLA_FORMATIVA_NOTAS PFN
	ON PFF.COD_PFF = PFN.COD_PFF
	WHERE PFN.COD_ALUMNO = @ALU_CODIGO_ORIGEN AND PF.ANO = @COA_ANO_ORIGEN
	AND PF.COM_COD = @COM_CODIGO_ORIGEN AND PF.CUAT = @COA_CUATRIMESTRE_ORIGEN AND PF.PLAN_COD =@PLAN_ORIGEN
 
   OPEN CPLANILLA_FORMATIVA 
   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   WHILE(@@FETCH_STATUS = 0)
   BEGIN
         INSERT INTO SEDESPEÑA.DBO.PLANILLA_FORMATIVA_FECHA
		 VALUES(CAST(@COD_PF AS nchar(10)),@NUMERO_E,@FECHA)

		 --OBTENGO ÚLTIMO @COD_PFF INSERTADO EN PLANILLA_FORMATIVA_FECHAS PARA INSERTAR EN DESTINO
		 SELECT @COD_PFF = SCOPE_IDENTITY()

       --INSERTO EN PLANILLA_FORMATIVA_NOTAS(@COD_PFF,COD_ALUMNO,NOTA)
		 INSERT INTO SEDESPEÑA.dbo.PLANILLA_FORMATIVA_NOTAS
		 VALUES(@COD_PFF,@ALU_CODIGO_DESTINO,@NOTA)

   FETCH CPLANILLA_FORMATIVA  INTO @NUMERO_E,@FECHA,@COD_ALUMNO,@NOTA
   END
   CLOSE CPLANILLA_FORMATIVA
   DEALLOCATE CPLANILLA_FORMATIVA

     
     


END
END


COMMIT TRAN
END TRY
BEGIN CATCH
ROLLBACK TRAN
END CATCH




