SELECT     LEGAJOS.APELLIDO, LEGAJOS.NOMBRE, LEGAJOS.NUMERO_DOC, LEGAJOS.MAIL, LEGAJOS.MAIL_2, VW_DESIGNACIONES.FAC_CODIGO, 
                      VW_DESIGNACIONES.FAC_DESCRIPCION, VW_DESIGNACIONES.CAR_CODIGO, VW_DESIGNACIONES.CAR_DESCRIPCION, 
                      VW_DESIGNACIONES.PES_CODIGO, VW_DESIGNACIONES.PES_DESCRIPCION, VW_DESIGNACIONES.MAT_CODIGO, 
                      VW_DESIGNACIONES.MAT_DESCRIPCION, VW_DESIGNACIONES.COMISION, VW_DESIGNACIONES.PLM_ANO, 
                      VW_DESIGNACIONES.PLM_CUATRIMESTRE, VW_DESIGNACIONES.SED_CODIGO, VW_DESIGNACIONES.SED_DESCRIPCION
FROM         LEGAJOS INNER JOIN
                      VW_DESIGNACIONES ON LEGAJOS.LEG_CODIGO = VW_DESIGNACIONES.DOC_CODIGO AND LEGAJOS.SEDE = VW_DESIGNACIONES.SEDE
WHERE     (VW_DESIGNACIONES.AÑO = 2013) AND (VW_DESIGNACIONES.CUATRIMESTRE = '2') AND (VW_DESIGNACIONES.ESTADO = '1')
ORDER BY VW_DESIGNACIONES.SED_DESCRIPCION, VW_DESIGNACIONES.FAC_DESCRIPCION, VW_DESIGNACIONES.CAR_DESCRIPCION, 
                      VW_DESIGNACIONES.PES_DESCRIPCION